# Generated by Django 4.2.1 on 2023-06-06 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('T', 'Top'), ('Btm', 'Bottom'), ('Jckt', 'Jacket'), ('Drs', 'Dress'), ('Jmp', 'Jumpsuit'), ('Sh', 'Shoes'), ('Acc', 'Accessory')], default=0, max_length=20)),
                ('size', models.CharField(choices=[('XL', 'Xtra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'Xtra Small')], default=0, max_length=20)),
                ('condition', models.CharField(choices=[('Bn', 'Brand New'), ('Ln', 'Like New'), ('UE', 'USED - Excellent'), ('UG', 'USED - Good'), ('UF', 'USED - Fair')], default=0, max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('clothing_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
