# Generated by Django 4.2.1 on 2023-06-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_clothes_likes_photo_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='clothes',
            new_name='clothing',
        ),
    ]
