# Generated by Django 4.2.1 on 2023-06-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_clothes_photo_clothing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='clothing',
            new_name='clothes',
        ),
    ]
