# Generated by Django 4.2.1 on 2023-06-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_clothing_photo_clothes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='clothes',
            new_name='clothing',
        ),
    ]
