# Generated by Django 4.2.1 on 2023-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_clothes_photo_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('XL', 'Xtra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'Xtra Small')], default=0, max_length=20),
        ),
    ]
